[package]
name = "policeunion"
version = "0.1.0"
edition = "2024"

[dependencies]
reqwest = "0.12.20"
serde_json = "1.0.140"
async-std = "1"
tokio = { version = "1.45.1", features = ["rt", "macros"] }
